-- +migrate Up
CREATE TABLE IF NOT EXISTS urls (
    id VARCHAR(50) PRIMARY KEY,
    uid BIGINT REFERENCES users(id) ON DELETE CASCADE,
    original_url TEXT NOT NULL,
    short_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


